services:
  nginx:
    image: nginx:alpine
    restart: always
    links:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/enabled:/etc/nginx/conf.d
      - ./data/nginx/snippets:/nginx/snippets
      - ./data/nginx/certificates:/nginx/certificates
    networks:
      - net
    volumes_from:
      - data

  php:
    image: php:8.0.0-fpm-alpine
    restart: always
    networks:
      - net
    volumes_from:
      - data
    command: sh -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && php-fpm"
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - net

  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root # Remove line for production
      PMA_PASSWORD: root # Remove line for production
    depends_on:
      - db
    networks:
      - net
    # ports:
    #   - "8080:80"
  data:
    image: alpine:latest
    command: echo "READY!!!"
    volumes:
      - ./data/vhosts:/vhosts
      - ./data/tmp:/tmp
    networks:
      - net
networks:
  net:
    driver: bridge
